//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLH
{
    using System;
    using System.Collections.Generic;
    
    public partial class DossierAdmission
    {
        public int IdAdmission { get; set; }
        public bool Chirurgie { get; set; }
        public Nullable<System.DateTime> DateAdmission { get; set; }
        public Nullable<System.DateTime> DateConge { get; set; }
        public Nullable<int> NSS { get; set; }
        public Nullable<int> NumLit { get; set; }
        public Nullable<int> IdMedecin { get; set; }
    
        public virtual Lit Lit { get; set; }
        public virtual Medecin Medecin { get; set; }
        public virtual Patient Patient { get; set; }

        // additional code
        private string nomMedecin;

        public string NomMedecin {
            get { return Medecin.Prenom + " " + Medecin.Nom; }
            set { nomMedecin = value; }
        }

    }
}
