//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLH
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NLHContext : DbContext
    {
        public NLHContext()
            : base("name=NLHContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompagnieAssurance> CompagnieAssurances { get; set; }
        public virtual DbSet<Departement> Departements { get; set; }
        public virtual DbSet<DossierAdmission> DossierAdmissions { get; set; }
        public virtual DbSet<Lit> Lits { get; set; }
        public virtual DbSet<Medecin> Medecins { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<TypeLit> TypeLits { get; set; }
    }
}
